# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        Symfony\Component\Security\Core\User\User: bcrypt
        AppBundle\Entity\User: argon2i

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    sarah:
                        password: '$2y$13$H/1ogHOYkwEAKnyV8R.BpeHbLCZ.Kp9Y6dxOjd.T.ZpS43//p4Iaa' #test
                        roles: 'ROLE_USER'
        database:
            entity:
                class: AppBundle\Entity\User
                property: email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/login$
            anonymous: ~
            
        secured_area:
            pattern: ^/
            provider: database
            form_login:
                login_path: /login
                check_path: /login_check
                username_parameter:  email
                password_parameter:  password
                always_use_default_target_path: true
            logout: ~

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
